name: GitHub CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  conda_asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_asan.sh
  conda_static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_conda_static.sh
  osx_heyoka_head:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_osx_heyoka_head.sh
  osx_heyoka_head_static:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: bash tools/gha_osx_heyoka_head_static.sh
  manylinux228-py311:
     runs-on: ubuntu-latest
     container:
      image: pagmo2/manylinux228_x86_64_with_deps:latest
      env:
        HEYOKA_PY_BUILD_TYPE: "Python311"
        # TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        # TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
     steps:
       - uses: actions/checkout@v3
       - name: Build
         run: bash tools/gha_manylinux.sh
  windows_2019_heyoka_head:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          channels: conda-forge
          channel-priority: strict
      - name: Build
        shell: pwsh
        run: |
          conda install -y python=3.10 git pybind11 numpy cmake llvmdev=15.0.2 tbb-devel tbb astroquery boost-cpp fmt spdlog sleef sympy cloudpickle zlib libzlib mppp numba
          git clone https://github.com/bluescarni/heyoka.git heyoka_cpp
          cd heyoka_cpp
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=C:\Miniconda\envs\test\Library -DCMAKE_INSTALL_PREFIX=C:\Miniconda\envs\test\Library -DBoost_NO_BOOST_CMAKE=ON -DHEYOKA_ENABLE_IPO=yes -DHEYOKA_WITH_SLEEF=yes -DHEYOKA_WITH_MPPP=yes
          cmake --build . --config Release --target install
          cd ..
          cd ..
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=C:\Miniconda\envs\test\Library -DCMAKE_INSTALL_PREFIX=C:\Miniconda\envs\test\Library -DBoost_NO_BOOST_CMAKE=ON -DHEYOKA_PY_ENABLE_IPO=yes
          cmake --build . --config Release --target install
          cd c:\
          python -c "import numba; from heyoka import test; test.run_test_suite()"
  binder_cache:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }} # This builds the container on mybinder.org with the branch that was pushed on.
